name: Trigger auto deployment for agritrust-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/agritrust-api-AutoDeployTrigger-18529b5b-8992-4cfc-bfca-eb0bb607cbd5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AGRITRUSTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AGRITRUSTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AGRITRUSTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acragrotrust.azurecr.io
          registryUsername: ${{ secrets.AGRITRUSTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AGRITRUSTAPI_REGISTRY_PASSWORD }}
          containerAppName: agritrust-api
          resourceGroup: agro_trust_rg
          imageToBuild: acragrotrust.azurecr.io/agritrust-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


